[package]
name = "akai"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = { version = "0.38.0", features = ["linked"] }
ash-window = "0.13.0"
winit = "0.29.15"
shaderc = "0.8.3"
log = "0.4.21"
gpu-allocator = { git = "https://github.com/Traverse-Research/gpu-allocator.git", rev = "4b5c0d4" }
egui = "0.24.1"
egui-ash = { version = "0.4.0", features = ["gpu-allocator"] }
glam = "0.28.0"
bytemuck = "1.16.1"

[dev-dependencies]

[[example]]
name = "draworchestra"